//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Entities (merged)

namespace Srk.BetaseriesApi {
    using System;
    
    /// <summary>
    /// Response format for 'comments/comment'.
    /// </summary>
    public class Comment {
        
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public string id { get; set; }
        
        /// <summary>
        /// Gets or sets the user_id.
        /// </summary>
        public int user_id { get; set; }
        
        /// <summary>
        /// Gets or sets the login.
        /// </summary>
        public string login { get; set; }
        
        /// <summary>
        /// Gets or sets the avatar.
        /// </summary>
        public string avatar { get; set; }
        
        /// <summary>
        /// Gets or sets the date.
        /// </summary>
        public DateTime date { get; set; }
        
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        public string text { get; set; }
        
        /// <summary>
        /// Gets or sets the inner_id.
        /// </summary>
        public int inner_id { get; set; }
        
        /// <summary>
        /// Gets or sets the in_reply_to.
        /// </summary>
        public int in_reply_to { get; set; }
    }
    
    /// <summary>
    /// Response format for 'comments/replies'.
    /// </summary>
    public class CommentReply {
    }
    
    /// <summary>
    /// Response format for 'messages/discussion'.
    /// </summary>
    public class MessageDiscussion {
    }
    
    /// <summary>
    /// Response format for 'messages/inbox'.
    /// </summary>
    public class MessageInbox {
    }
    
    /// <summary>
    /// Response format for 'messages/message'.
    /// </summary>
    public class MessageMessage {
        
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int id { get; set; }
        
        /// <summary>
        /// Gets or sets the message_id.
        /// </summary>
        public int message_id { get; set; }
        
        /// <summary>
        /// Gets or sets the inner_id.
        /// </summary>
        public int inner_id { get; set; }
        
        /// <summary>
        /// Gets or sets the sender.
        /// </summary>
        public SenderClass sender { get; set; }
        
        public class SenderClass {
            
            /// <summary>
            /// Gets or sets the id.
            /// </summary>
            public int id { get; set; }
            
            /// <summary>
            /// Gets or sets the login.
            /// </summary>
            public string login { get; set; }
        }
        
        /// <summary>
        /// Gets or sets the recipient.
        /// </summary>
        public RecipientClass recipient { get; set; }
        
        public class RecipientClass {
            
            /// <summary>
            /// Gets or sets the id.
            /// </summary>
            public int id { get; set; }
            
            /// <summary>
            /// Gets or sets the login.
            /// </summary>
            public string login { get; set; }
        }
        
        /// <summary>
        /// Gets or sets the date.
        /// </summary>
        public DateTime date { get; set; }
        
        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        public string title { get; set; }
        
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        public string text { get; set; }
        
        /// <summary>
        /// Gets or sets the unread.
        /// </summary>
        public bool unread { get; set; }
        
        /// <summary>
        /// Gets or sets the has_unread.
        /// </summary>
        public bool has_unread { get; set; }
    }
    
    /// <summary>
    /// Response format for 'messages/read'.
    /// </summary>
    public class MessageRead {
        
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int id { get; set; }
        
        /// <summary>
        /// Gets or sets the message_id.
        /// </summary>
        public int message_id { get; set; }
        
        /// <summary>
        /// Gets or sets the inner_id.
        /// </summary>
        public int inner_id { get; set; }
        
        /// <summary>
        /// Gets or sets the sender.
        /// </summary>
        public SenderClass sender { get; set; }
        
        public class SenderClass {
            
            /// <summary>
            /// Gets or sets the id.
            /// </summary>
            public int id { get; set; }
            
            /// <summary>
            /// Gets or sets the login.
            /// </summary>
            public string login { get; set; }
        }
        
        /// <summary>
        /// Gets or sets the recipient.
        /// </summary>
        public RecipientClass recipient { get; set; }
        
        public class RecipientClass {
            
            /// <summary>
            /// Gets or sets the id.
            /// </summary>
            public int id { get; set; }
            
            /// <summary>
            /// Gets or sets the login.
            /// </summary>
            public string login { get; set; }
        }
        
        /// <summary>
        /// Gets or sets the date.
        /// </summary>
        public DateTime date { get; set; }
        
        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        public string title { get; set; }
        
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        public string text { get; set; }
        
        /// <summary>
        /// Gets or sets the unread.
        /// </summary>
        public bool unread { get; set; }
        
        /// <summary>
        /// Gets or sets the has_unread.
        /// </summary>
        public bool has_unread { get; set; }
    }
    
    /// <summary>
    /// Response format for 'shows/characters'.
    /// </summary>
    public class ShowCharacter {
    }
    
    /// <summary>
    /// Response format for 'shows/pictures'.
    /// </summary>
    public class ShowPicture {
    }
    
    /// <summary>
    /// Response format for 'subtitles/episode'.
    /// </summary>
    public class SubtitleEpisode {
    }
    
    /// <summary>
    /// Response format for 'subtitles/last'.
    /// </summary>
    public class SubtitleLast {
    }
    
    /// <summary>
    /// Response format for 'subtitles/report'.
    /// </summary>
    public class SubtitleReport {
    }
    
    /// <summary>
    /// Response format for 'subtitles/show'.
    /// </summary>
    public class SubtitleShow {
    }
    
    /// <summary>
    /// Response format for 'timeline/friends'.
    /// </summary>
    public class TimelineFriend {
    }
    
    /// <summary>
    /// Response format for 'timeline/home'.
    /// </summary>
    public class TimelineHome {
    }
    
    /// <summary>
    /// Response format for 'timeline/member'.
    /// </summary>
    public class TimelineMember {
    }
}

#endregion


#region ArgumentEnums (merged)

namespace Srk.BetaseriesApi {
    using System;
    
    /// <summary>
    /// Response format id 'episode|show|member|movie'.
    /// </summary>
    /// <remark>
    /// ARGID:episode|show|member|movie
    /// ARGDESC:Type d&#x27;élément : episode|show|member|movie
    /// </remark>
    public enum EntityType {
        episode,
        show,
        member,
        movie,
    }
    
    /// <summary>
    /// Response format id 'all|vovf|vo|vf'.
    /// </summary>
    /// <remark>
    /// ARGID:all|vovf|vo|vf
    /// ARGDESC:Affiche les épisodes avec certains sous-titres disponibles : all|vovf|vo|vf (Facultatif)
    /// </remark>
    public enum SubtitleFilter {
        all,
        vovf,
        vo,
        vf,
    }
    
    /// <summary>
    /// Response format id 'open|requests|friends|nobody'.
    /// </summary>
    /// <remark>
    /// ARGID:open|requests|friends|nobody
    /// ARGDESC:Valeur de l&#x27;option (1 ou 0, pour friendship : open|requests|friends|nobody)
    /// </remark>
    public enum ProfileConfidentiality {
        open,
        requests,
        friends,
        nobody,
    }
    
    /// <summary>
    /// Response format id 'title|popularity'.
    /// </summary>
    /// <remark>
    /// ARGID:title|popularity
    /// ARGDESC:Ordre de retour (title|popularity), par défaut title
    /// </remark>
    public enum TitlePopularity {
        title,
        popularity,
    }
    
    /// <summary>
    /// Response format id 'title|popularity|followers'.
    /// </summary>
    /// <remark>
    /// ARGID:title|popularity|followers
    /// ARGDESC:Ordre de retour (title|popularity|followers), par défaut title
    /// </remark>
    public enum TitlePopularityFollower {
        title,
        popularity,
        followers,
    }
}

#endregion


#region Services

namespace Srk.BetaseriesApi {
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class BetaseriesClient {

        private BetaseriesCommentsClient commentsClient;
        public BetaseriesCommentsClient Comments {
            get { return this.commentsClient ?? (this.commentsClient = new BetaseriesCommentsClient(this)); }
        }

        private BetaseriesEpisodesClient episodesClient;
        public BetaseriesEpisodesClient Episodes {
            get { return this.episodesClient ?? (this.episodesClient = new BetaseriesEpisodesClient(this)); }
        }

        private BetaseriesFriendsClient friendsClient;
        public BetaseriesFriendsClient Friends {
            get { return this.friendsClient ?? (this.friendsClient = new BetaseriesFriendsClient(this)); }
        }

        private BetaseriesMembersClient membersClient;
        public BetaseriesMembersClient Members {
            get { return this.membersClient ?? (this.membersClient = new BetaseriesMembersClient(this)); }
        }

        private BetaseriesMessagesClient messagesClient;
        public BetaseriesMessagesClient Messages {
            get { return this.messagesClient ?? (this.messagesClient = new BetaseriesMessagesClient(this)); }
        }

        private BetaseriesMoviesClient moviesClient;
        public BetaseriesMoviesClient Movies {
            get { return this.moviesClient ?? (this.moviesClient = new BetaseriesMoviesClient(this)); }
        }

        private BetaseriesPicturesClient picturesClient;
        public BetaseriesPicturesClient Pictures {
            get { return this.picturesClient ?? (this.picturesClient = new BetaseriesPicturesClient(this)); }
        }

        private BetaseriesPlanningClient planningClient;
        public BetaseriesPlanningClient Planning {
            get { return this.planningClient ?? (this.planningClient = new BetaseriesPlanningClient(this)); }
        }

        private BetaseriesShowsClient showsClient;
        public BetaseriesShowsClient Shows {
            get { return this.showsClient ?? (this.showsClient = new BetaseriesShowsClient(this)); }
        }

        private BetaseriesSubtitlesClient subtitlesClient;
        public BetaseriesSubtitlesClient Subtitles {
            get { return this.subtitlesClient ?? (this.subtitlesClient = new BetaseriesSubtitlesClient(this)); }
        }

        private BetaseriesTimelineClient timelineClient;
        public BetaseriesTimelineClient Timeline {
            get { return this.timelineClient ?? (this.timelineClient = new BetaseriesTimelineClient(this)); }
        }
    }


    public partial class BetaseriesCommentsClient {
        private readonly BetaseriesClient client;

        public BetaseriesCommentsClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Envoie un commentaire pour l'élément spécifié.
        /// Call for POST 'comments/comment'.
        /// </summary>
        /// <param name="type">Type d&#x27;élément : episode|show|member|movie</param>
        /// <param name="id">ID de l&#x27;élément en question</param>
        /// <param name="text">Texte du commentaire</param>
        /// <param name="in_reply_to">Si c&#x27;est une réponse, inner_id du commentaire correspondant (Facultatif)</param>
        public Srk.BetaseriesApi.Comment Post(EntityType type, string id, string text, string in_reply_to) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("type", type.ToString()));
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("text", text));
            parameters.Add(new KVP<string, string>("in_reply_to", in_reply_to));
            var response = this.client.ExecuteQuery("POST", "comments/comment", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.Comment>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Supprime un commentaire de l'utilisateur identifié.
        /// Call for DELETE 'comments/comment'.
        /// </summary>
        /// <param name="id">ID du commentaire</param>
        public Srk.BetaseriesApi.Comment Delete(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "comments/comment", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.Comment>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Récupère les commentaires pour un élément donné.
        /// Call for GET 'comments/comments'.
        /// </summary>
        /// <param name="type">Type d&#x27;élément : episode|show|member|movie</param>
        /// <param name="id">ID de l&#x27;élément en question</param>
        /// <param name="nbpp">Nombre de commentaires par page</param>
        /// <param name="since_id">ID du dernier commentaire reçu (Facultatif)</param>
        /// <param name="order">Ordre chronologique de retour, desc ou asc (Défaut asc)</param>
        /// <param name="replies">Inclure les réponses aux commentaires (1 ou 0, par défaut 1)</param>
        public Srk.BetaseriesApi.CommentComment Get(EntityType type, string id, string nbpp, string since_id, string order, string replies) {
            var parameters = new List<KVP<string, string>>(6);
            parameters.Add(new KVP<string, string>("type", type.ToString()));
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("nbpp", nbpp));
            parameters.Add(new KVP<string, string>("since_id", since_id));
            parameters.Add(new KVP<string, string>("order", order));
            parameters.Add(new KVP<string, string>("replies", replies));
            var response = this.client.ExecuteQuery("GET", "comments/comments", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.CommentComment>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Récupère les réponses d'un commentaire donné.
        /// Call for GET 'comments/replies'.
        /// </summary>
        /// <param name="id">ID du commentaire</param>
        /// <param name="order">Ordre chronologique de retour, desc ou asc (Défaut asc)</param>
        public Srk.BetaseriesApi.CommentReply Reply(string id, string order) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("order", order));
            var response = this.client.ExecuteQuery("GET", "comments/replies", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.CommentReply>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Inscrit le membre aux notifications e-mail pour l'élément donné.
        /// Call for POST 'comments/subscription'.
        /// </summary>
        /// <param name="type">Type d&#x27;élément : episode|show|member|movie</param>
        /// <param name="id">ID de l&#x27;élément en question</param>
        public void Subscribe(EntityType type, string id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("type", type.ToString()));
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("POST", "comments/subscription", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Désinscrit le membre aux notifications e-mail pour l'élément donné.
        /// Call for DELETE 'comments/subscription'.
        /// </summary>
        /// <param name="type">Type d&#x27;élément : episode|show|member|movie</param>
        /// <param name="id">ID de l&#x27;élément en question</param>
        public void Unsubscribe(EntityType type, string id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("type", type.ToString()));
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "comments/subscription", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesEpisodesClient {
        private readonly BetaseriesClient client;

        public BetaseriesEpisodesClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Affiche les informations d'un épisode.
        /// Call for GET 'episodes/display'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode. Vous pouvez en mettre plusieurs en les séparant par un virgule (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB. Vous pouvez en mettre plusieurs en les séparant par un virgule (Facultatif si id renseigné)</param>
        /// <param name="subtitles">Affiche les sous-titres si renseigné (Facultatif)</param>
        public void GetById(string id, string thetvdb_id, string subtitles) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("subtitles", subtitles));
            var response = this.client.ExecuteQuery("GET", "episodes/display", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Marque un épisode comme téléchargé.
        /// Call for POST 'episodes/downloaded'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB (Facultatif si id renseigné)</param>
        public void MarkDownloaded(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("POST", "episodes/downloaded", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Enlève le marquage d'un épisode comme téléchargé.
        /// Call for DELETE 'episodes/downloaded'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB (Facultatif si id renseigné)</param>
        public void UnmarkDownloaded(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("DELETE", "episodes/downloaded", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère la liste des épisodes à voir.
        /// Call for GET 'episodes/list'.
        /// </summary>
        /// <param name="subtitles">Affiche les épisodes avec certains sous-titres disponibles : all|vovf|vo|vf (Facultatif)</param>
        /// <param name="limit">Limite à un nombre d&#x27;épisodes par série (Facultatif)</param>
        /// <param name="showId">ID de la série (Facultatif)</param>
        /// <param name="userId">ID du membre (Facultatif, par défaut membre identifié)</param>
        public void List(SubtitleFilter subtitles, string limit, string showId, string userId) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("subtitles", subtitles.ToString()));
            parameters.Add(new KVP<string, string>("limit", limit));
            parameters.Add(new KVP<string, string>("showId", showId));
            parameters.Add(new KVP<string, string>("userId", userId));
            var response = this.client.ExecuteQuery("GET", "episodes/list", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Note un épisode.
        /// Call for POST 'episodes/note'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB (Facultatif si id renseigné)</param>
        /// <param name="note">Note attribuée de 1 à 5</param>
        public void SetMark(string id, string thetvdb_id, string note) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("note", note));
            var response = this.client.ExecuteQuery("POST", "episodes/note", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime une note d'un épisode.
        /// Call for DELETE 'episodes/note'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB (Facultatif si id renseigné)</param>
        public void DeleteMark(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("DELETE", "episodes/note", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les informations d'un épisode en fonction du nom de fichier
        /// Call for GET 'episodes/scraper'.
        /// </summary>
        /// <param name="file">Nom du fichier à traiter</param>
        public void EpisodeScraper(string file) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("file", file));
            var response = this.client.ExecuteQuery("GET", "episodes/scraper", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les informations d'un épisode en fonction d'informations.
        /// Call for GET 'episodes/search'.
        /// </summary>
        /// <param name="show_id">ID de la série pour l&#x27;épisode à chercher</param>
        /// <param name="number">Numéro de la série, soit SxxExx soit le numéro global</param>
        /// <param name="subtitles">Si spécifié, retourne les sous-titres des épisodes</param>
        public void Search(string show_id, string number, string subtitles) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("show_id", show_id));
            parameters.Add(new KVP<string, string>("number", number));
            parameters.Add(new KVP<string, string>("subtitles", subtitles));
            var response = this.client.ExecuteQuery("GET", "episodes/search", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Marque un épisode comme vu. Vous pouvez spécifier plusieurs épisodes en séparant les ID par une virgule.
        /// Call for POST 'episodes/watched'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB (Facultatif si id renseigné)</param>
        /// <param name="bulk">Si bulk est spécifié, tous les épisodes précédents seront aussi marqués comme vus (défaut à true)</param>
        /// <param name="delete">Si delete est spécifié, tous les épisodes d&#x27;après ne seront plus marqués comme vus</param>
        /// <param name="note">Si la note est spécifiée entre 1 et 5, donne une note à l&#x27;épisode</param>
        public void MarkWatched(string id, string thetvdb_id, string bulk, string delete, string note) {
            var parameters = new List<KVP<string, string>>(5);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("bulk", bulk));
            parameters.Add(new KVP<string, string>("delete", delete));
            parameters.Add(new KVP<string, string>("note", note));
            var response = this.client.ExecuteQuery("POST", "episodes/watched", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Enlève le marquage d'un épisode comme vu.
        /// Call for DELETE 'episodes/watched'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de l&#x27;épisode sur TheTVDB (Facultatif si id renseigné)</param>
        public void UnmarkWatched(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("DELETE", "episodes/watched", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesFriendsClient {
        private readonly BetaseriesClient client;

        public BetaseriesFriendsClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Bloque un utilisateur.
        /// Call for POST 'friends/block'.
        /// </summary>
        /// <param name="id">ID du membre à bloquer</param>
        public void Block(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("POST", "friends/block", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime le blocage d'un utilisateur.
        /// Call for DELETE 'friends/block'.
        /// </summary>
        /// <param name="id">ID du membre à débloquer</param>
        public void Unblock(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "friends/block", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Ajoute un ami dans le compte de l'utilisateur.
        /// Call for POST 'friends/friend'.
        /// </summary>
        /// <param name="id">ID du membre à ajouter en ami</param>
        public void Friend(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("POST", "friends/friend", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime un ami du compte de l'utilisateur.
        /// Call for DELETE 'friends/friend'.
        /// </summary>
        /// <param name="id">ID du membre à supprimer</param>
        public void Unfriend(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "friends/friend", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère la liste des amis du membre.
        /// Call for GET 'friends/list'.
        /// </summary>
        /// <param name="id">ID du membre, facultatif, si non renseigné utilise le membre identifié. Si renseigné, blocked=false.</param>
        /// <param name="blocked">Si spécifié, retourne la liste des personnes bloquées</param>
        public void GetFriends(string id, string blocked) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("blocked", blocked));
            var response = this.client.ExecuteQuery("GET", "friends/list", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère la liste des demandes envoyées par l'utilisateur.
        /// Call for GET 'friends/requests'.
        /// </summary>
        /// <param name="received">Si spécifié, retourne la liste des demandes reçues</param>
        public void GetFriendRequests(string received) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("received", received));
            var response = this.client.ExecuteQuery("GET", "friends/requests", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesMembersClient {
        private readonly BetaseriesClient client;

        public BetaseriesMembersClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Récupère un token d'accès avec le code fourni par l'identification OAuth 2.
        /// Call for POST 'members/access_token'.
        /// </summary>
        /// <param name="client_id">Votre clé API.</param>
        /// <param name="client_secret">La clé secrète fournie dans les informations de votre clé.</param>
        /// <param name="redirect_uri">L&#x27;adresse de callback que vous aviez déjà renseignée pour la première partie.</param>
        /// <param name="code">Code récupéré par la première partie de l&#x27;identification.</param>
        public void GetOAuth2AccessToken(string client_id, string client_secret, string redirect_uri, string code) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("client_id", client_id));
            parameters.Add(new KVP<string, string>("client_secret", client_secret));
            parameters.Add(new KVP<string, string>("redirect_uri", redirect_uri));
            parameters.Add(new KVP<string, string>("code", code));
            var response = this.client.ExecuteQuery("POST", "members/access_token", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Identification classique du membre.
        /// Call for POST 'members/auth'.
        /// </summary>
        /// <param name="login">Identifiant (login ou e-mail)</param>
        /// <param name="password">Mot de passe encrypté en MD5</param>
        public void ClassicAuthenticate(string login, string password) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("login", login));
            parameters.Add(new KVP<string, string>("password", password));
            var response = this.client.ExecuteQuery("POST", "members/auth", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Uploade et remplace l'avatar de l'utilisateur identifié.
        /// Call for POST 'members/avatar'.
        /// </summary>
        /// <param name="avatar">Image à utiliser pour l&#x27;avatar de l&#x27;utilisateur.</param>
        public void SetProfilePicture(string avatar) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("avatar", avatar));
            var response = this.client.ExecuteQuery("POST", "members/avatar", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime l'avatar de l'utilisateur identifié.
        /// Call for DELETE 'members/avatar'.
        /// </summary>
        public void DeleteProfilePicture() {
            var parameters = new List<KVP<string, string>>(0);
            var response = this.client.ExecuteQuery("DELETE", "members/avatar", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche les badges du membre.
        /// Call for GET 'members/badges'.
        /// </summary>
        /// <param name="id">ID du membre</param>
        public void GetBadges(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("GET", "members/badges", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Détruit le token actif.
        /// Call for POST 'members/destroy'.
        /// </summary>
        public void DestroyToken() {
            var parameters = new List<KVP<string, string>>(0);
            var response = this.client.ExecuteQuery("POST", "members/destroy", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Renvoie les informations d'un membre, du membre identifié par défaut.
        /// Call for GET 'members/infos'.
        /// </summary>
        /// <param name="id">ID du membre</param>
        /// <param name="summary">N&#x27;affiche que les informations et pas les séries / films du compte (Défaut false)</param>
        public void GetProfile(string id, string summary) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("summary", summary));
            var response = this.client.ExecuteQuery("GET", "members/infos", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Vérifie que le token est actif.
        /// Call for GET 'members/is_active'.
        /// </summary>
        public void VerifyToken() {
            var parameters = new List<KVP<string, string>>(0);
            var response = this.client.ExecuteQuery("GET", "members/is_active", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Envoie un e-mail pour réinitialiser le mot de passe.
        /// Call for POST 'members/lost'.
        /// </summary>
        /// <param name="find">Adresse e-mail ou nom de l&#x27;utilisateur</param>
        public void ResetPassword(string find) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("find", find));
            var response = this.client.ExecuteQuery("POST", "members/lost", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche les dernières notifications du membre. Types : badge, banner, bugs, character, commentaire, dons, episode, facebook, film, forum, friend, message, quizz, recommend, site, subtitles, video.
        /// Call for GET 'members/notifications'.
        /// </summary>
        /// <param name="since_id">Dernier ID (Facultatif)</param>
        /// <param name="number">Nombre de notifications, maximum 100 (Facultatif, défaut 10)</param>
        /// <param name="sort">Tri descendant ou ascendant (ASC ou DESC, défaut DESC)</param>
        /// <param name="types">Retourner uniquement certains types séparés par une virgule (Facultatif)</param>
        /// <param name="auto_delete">Suppression automatique des notifications (Facultatif, défaut false)</param>
        public void MemberNotification(string since_id, string number, string sort, string types, string auto_delete) {
            var parameters = new List<KVP<string, string>>(5);
            parameters.Add(new KVP<string, string>("since_id", since_id));
            parameters.Add(new KVP<string, string>("number", number));
            parameters.Add(new KVP<string, string>("sort", sort));
            parameters.Add(new KVP<string, string>("types", types));
            parameters.Add(new KVP<string, string>("auto_delete", auto_delete));
            var response = this.client.ExecuteQuery("GET", "members/notifications", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Modifie une option de l'utilisateur.
        /// Call for POST 'members/option'.
        /// </summary>
        /// <param name="name">Nom de l&#x27;option (downloaded, global, notation, timelag, friendship)</param>
        /// <param name="value">Valeur de l&#x27;option (1 ou 0, pour friendship : open|requests|friends|nobody)</param>
        public void MemberOption(string name, ProfileConfidentiality value) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("name", name));
            parameters.Add(new KVP<string, string>("value", value.ToString()));
            var response = this.client.ExecuteQuery("POST", "members/option", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les options (sous-titres) du membre.
        /// Call for GET 'members/options'.
        /// </summary>
        public void MemberOption() {
            var parameters = new List<KVP<string, string>>(0);
            var response = this.client.ExecuteQuery("GET", "members/options", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Recherche des membres.
        /// Call for GET 'members/search'.
        /// </summary>
        /// <param name="login">Nom de l&#x27;utilisateur, 2 caractères minimum. Vous pouvez utiliser % comme wildcard.</param>
        public void MemberSearch(string login) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("login", login));
            var response = this.client.ExecuteQuery("GET", "members/search", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Crée un nouveau compte membre sur BetaSeries.
        /// Call for POST 'members/signup'.
        /// </summary>
        /// <param name="login">Nom d&#x27;utilisateur</param>
        /// <param name="password">Mot de passe en MD5 — Facultatif : S&#x27;il n&#x27;est pas fourni il sera généré et envoyé dans l&#x27;e-mail</param>
        /// <param name="email">Adresse e-mail</param>
        public void MemberSignup(string login, string password, string email) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("login", login));
            parameters.Add(new KVP<string, string>("password", password));
            parameters.Add(new KVP<string, string>("email", email));
            var response = this.client.ExecuteQuery("POST", "members/signup", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Cherche les membres parmi les amis du compte.
        /// Call for POST 'members/sync'.
        /// </summary>
        /// <param name="mails">Tableau POST des adresses e-mail à chercher</param>
        public void MemberSync(string[] mails) {
            var parameters = new List<KVP<string, string>>(1);
            foreach (var argValue in mails) {
                parameters.Add(new KVP<string, string>("mails[]", argValue));
            }
            var response = this.client.ExecuteQuery("POST", "members/sync", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Retourne les possibilités de noms d'utilisateur libres sur BetaSeries.
        /// Call for GET 'members/username'.
        /// </summary>
        /// <param name="username">Nom d&#x27;utilisateur</param>
        public void MemberUsername(string username) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("username", username));
            var response = this.client.ExecuteQuery("GET", "members/username", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesMessagesClient {
        private readonly BetaseriesClient client;

        public BetaseriesMessagesClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Récupère une discussion identifiée par l'ID du premier message.
        /// Call for GET 'messages/discussion'.
        /// </summary>
        /// <param name="id">ID du premier message de la discussion</param>
        public Srk.BetaseriesApi.MessageDiscussion MessageDiscussion(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("GET", "messages/discussion", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.MessageDiscussion>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Récupère la boîte de réception du membre identifié, par pages de 20.
        /// Call for GET 'messages/inbox'.
        /// </summary>
        /// <param name="page">Numéro de la page, 1 par défaut</param>
        public Srk.BetaseriesApi.MessageInbox MessageInbox(string page) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("page", page));
            var response = this.client.ExecuteQuery("GET", "messages/inbox", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.MessageInbox>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Supprime un message que vous avez écrit.
        /// Call for DELETE 'messages/message'.
        /// </summary>
        /// <param name="id">ID du message à supprimer — Si c&#x27;est le premier d&#x27;une discussion, toute la discussion est supprimée</param>
        public Srk.BetaseriesApi.MessageMessage DeleteMessageMessage(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "messages/message", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.MessageMessage>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Envoie un message à un autre membre du site.
        /// Call for POST 'messages/message'.
        /// </summary>
        /// <param name="to">ID du membre destinataire (obligatoire si premier message)</param>
        /// <param name="text">Texte du message</param>
        /// <param name="title">Titre du message (obligatoire si premier message)</param>
        /// <param name="id">ID du premier message de la discussion (facultatif)</param>
        public Srk.BetaseriesApi.MessageMessage MessageMessage(string to, string text, string title, string id) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("to", to));
            parameters.Add(new KVP<string, string>("text", text));
            parameters.Add(new KVP<string, string>("title", title));
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("POST", "messages/message", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.MessageMessage>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Marque un message comme lu.
        /// Call for POST 'messages/read'.
        /// </summary>
        /// <param name="id">ID du message à marquer comme lu</param>
        public Srk.BetaseriesApi.MessageRead MessageRead(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("POST", "messages/read", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.MessageRead>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }
    }

    public partial class BetaseriesMoviesClient {
        private readonly BetaseriesClient client;

        public BetaseriesMoviesClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Affiche la liste de tous les films.
        /// Call for GET 'movies/list'.
        /// </summary>
        /// <param name="start">Nombre de démarrage pour la liste des films (facultatif, défaut 0)</param>
        /// <param name="limit">Limite du nombre de films à afficher (maximum 1000) (facultatif)</param>
        /// <param name="order">Spécifie l&#x27;ordre de retour : alphabetical, popularity (facultatif)</param>
        public void MovyList(string start, string limit, string order) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("start", start));
            parameters.Add(new KVP<string, string>("limit", limit));
            parameters.Add(new KVP<string, string>("order", order));
            var response = this.client.ExecuteQuery("GET", "movies/list", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche la liste de tous les films du membre.
        /// Call for GET 'movies/member'.
        /// </summary>
        /// <param name="state">0 = à voir, 1 = vu, 2 = ne veut pas voir (0 par défaut)</param>
        /// <param name="start">Nombre de démarrage pour la liste des films (facultatif, défaut 0)</param>
        /// <param name="limit">Limite du nombre de films à afficher (maximum 1000) (facultatif)</param>
        /// <param name="order">Spécifie l&#x27;ordre de retour : alphabetical, popularity (facultatif)</param>
        public void MovyMember(string state, string start, string limit, string order) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("state", state));
            parameters.Add(new KVP<string, string>("start", start));
            parameters.Add(new KVP<string, string>("limit", limit));
            parameters.Add(new KVP<string, string>("order", order));
            var response = this.client.ExecuteQuery("GET", "movies/member", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche les détails d'un film.
        /// Call for GET 'movies/movie'.
        /// </summary>
        /// <param name="id">ID du film</param>
        public void MovyMovie(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("GET", "movies/movie", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Ajoute ou met à jour le film dans les films du membre.
        /// Call for POST 'movies/movie'.
        /// </summary>
        /// <param name="id">ID du film</param>
        /// <param name="mail">Activer les alertes e-mail (0 ou 1, 1 par défaut)</param>
        /// <param name="twitter">Activer les alertes Twitter (0 ou 1, 1 par défaut)</param>
        /// <param name="state">0 = à voir, 1 = vu, 2 = ne veut pas voir (0 par défaut)</param>
        /// <param name="profile">Afficher sur le profil (0 ou 1, 1 par défaut)</param>
        public void MovyMovie(string id, string mail, string twitter, string state, string profile) {
            var parameters = new List<KVP<string, string>>(5);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("mail", mail));
            parameters.Add(new KVP<string, string>("twitter", twitter));
            parameters.Add(new KVP<string, string>("state", state));
            parameters.Add(new KVP<string, string>("profile", profile));
            var response = this.client.ExecuteQuery("POST", "movies/movie", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime un film du compte membre.
        /// Call for DELETE 'movies/movie'.
        /// </summary>
        /// <param name="id">ID du film</param>
        public void DeleteMovyMovie(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "movies/movie", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche un film au hasard.
        /// Call for GET 'movies/random'.
        /// </summary>
        /// <param name="nb">Nombre de films à afficher, par défaut 1</param>
        public void MovyRandom(string nb) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("nb", nb));
            var response = this.client.ExecuteQuery("GET", "movies/random", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les informations d'un film en fonction du nom de fichier
        /// Call for GET 'movies/scraper'.
        /// </summary>
        /// <param name="file">Nom du fichier à traiter</param>
        public void MovyScraper(string file) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("file", file));
            var response = this.client.ExecuteQuery("GET", "movies/scraper", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Recherche un film par critères.
        /// Call for GET 'movies/search'.
        /// </summary>
        /// <param name="title">Titre recherché (facultatif si order=popularity)</param>
        /// <param name="order">Ordre de retour (title|popularity), par défaut title</param>
        /// <param name="nbpp">Nombre de résultats par page, par défaut 5, maximum 100</param>
        /// <param name="page">Numéro de la page, par défaut 1</param>
        public void MovySearch(string title, TitlePopularity order, string nbpp, string page) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("title", title));
            parameters.Add(new KVP<string, string>("order", order.ToString()));
            parameters.Add(new KVP<string, string>("nbpp", nbpp));
            parameters.Add(new KVP<string, string>("page", page));
            var response = this.client.ExecuteQuery("GET", "movies/search", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesPicturesClient {
        private readonly BetaseriesClient client;

        public BetaseriesPicturesClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Retourne une image du badge (32x32).
        /// Call for GET 'pictures/badges'.
        /// </summary>
        /// <param name="id">ID du badge</param>
        public void PictureBadge(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("GET", "pictures/badges", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Retourne une image du personnage.
        /// Call for GET 'pictures/characters'.
        /// </summary>
        /// <param name="id">ID du personnage</param>
        /// <param name="width">Largeur désirée (facultatif, défaut 250)</param>
        /// <param name="height">Hauteur désirée (facultatif, défaut 375)</param>
        public void PictureCharacter(string id, string width, string height) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("width", width));
            parameters.Add(new KVP<string, string>("height", height));
            var response = this.client.ExecuteQuery("GET", "pictures/characters", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Retourne une image de l'épisode.
        /// Call for GET 'pictures/episodes'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode</param>
        /// <param name="width">Largeur désirée (facultatif)</param>
        /// <param name="height">Hauteur désirée (facultatif)</param>
        public void PictureEpisode(string id, string width, string height) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("width", width));
            parameters.Add(new KVP<string, string>("height", height));
            var response = this.client.ExecuteQuery("GET", "pictures/episodes", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Retourne une image du membre.
        /// Call for GET 'pictures/members'.
        /// </summary>
        /// <param name="id">ID du membre</param>
        /// <param name="width">Largeur désirée (facultatif)</param>
        /// <param name="height">Hauteur désirée (facultatif)</param>
        public void PictureMember(string id, string width, string height) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("width", width));
            parameters.Add(new KVP<string, string>("height", height));
            var response = this.client.ExecuteQuery("GET", "pictures/members", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Retourne une image du film.
        /// Call for GET 'pictures/movies'.
        /// </summary>
        /// <param name="id">ID du film</param>
        /// <param name="width">Largeur désirée (facultatif, défaut 250)</param>
        /// <param name="height">Hauteur désirée (facultatif, défaut 375)</param>
        public void PictureMovy(string id, string width, string height) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("width", width));
            parameters.Add(new KVP<string, string>("height", height));
            var response = this.client.ExecuteQuery("GET", "pictures/movies", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Retourne une image de la série.
        /// Call for GET 'pictures/shows'.
        /// </summary>
        /// <param name="id">ID de la série</param>
        /// <param name="width">Largeur désirée (facultatif)</param>
        /// <param name="height">Hauteur désirée (facultatif)</param>
        /// <param name="picked">Prendre l&#x27;image votée par la communauté (banner ou show, facultatif)</param>
        public void PictureShow(string id, string width, string height, string picked) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("width", width));
            parameters.Add(new KVP<string, string>("height", height));
            parameters.Add(new KVP<string, string>("picked", picked));
            var response = this.client.ExecuteQuery("GET", "pictures/shows", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesPlanningClient {
        private readonly BetaseriesClient client;

        public BetaseriesPlanningClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Affiche tous les épisodes diffusés les 8 derniers jours jusqu'aux 8 prochains jours.
        /// Call for GET 'planning/general'.
        /// </summary>
        /// <param name="date">Date d&#x27;origine (YYYY-MM-JJ — Facultatif, par défaut &quot;now&quot;)</param>
        /// <param name="before">Nombre de jours avant (Facultatif, par défaut 8)</param>
        /// <param name="after">Nombre de jours après (Facultatif, par défaut 8)</param>
        /// <param name="type">Type d&#x27;épisodes à afficher : &quot;all&quot; ou &quot;premieres&quot; (Facultatif, par défaut &quot;all&quot;)</param>
        public void PlanningGeneral(string date, string before, string after, string type) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("date", date));
            parameters.Add(new KVP<string, string>("before", before));
            parameters.Add(new KVP<string, string>("after", after));
            parameters.Add(new KVP<string, string>("type", type));
            var response = this.client.ExecuteQuery("GET", "planning/general", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche uniquement le premier épisode des prochaines séries qui vont être diffusées.
        /// Call for GET 'planning/incoming'.
        /// </summary>
        public void PlanningIncoming() {
            var parameters = new List<KVP<string, string>>(0);
            var response = this.client.ExecuteQuery("GET", "planning/incoming", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche le planning du membre identifié ou d'un autre membre.
        /// Call for GET 'planning/member'.
        /// </summary>
        /// <param name="id">ID du membre (Facultatif si identifié)</param>
        /// <param name="unseen">N&#x27;affiche que les épisodes non-vus</param>
        /// <param name="month">Affiche le planning du mois spécifié (format YYYY-MM)</param>
        public void PlanningMember(string id, string unseen, string month) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("unseen", unseen));
            parameters.Add(new KVP<string, string>("month", month));
            var response = this.client.ExecuteQuery("GET", "planning/member", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesShowsClient {
        private readonly BetaseriesClient client;

        public BetaseriesShowsClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Archive une série dans le compte du membre.
        /// Call for POST 'shows/archive'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public void ShowArchive(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("POST", "shows/archive", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Sort une série des archives du compte du membre.
        /// Call for DELETE 'shows/archive'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public void DeleteShowArchive(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("DELETE", "shows/archive", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les personnages de la série, ajoutés par les membres de BetaSeries.
        /// Call for GET 'shows/characters'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public Srk.BetaseriesApi.ShowCharacter ShowCharacter(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("GET", "shows/characters", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.ShowCharacter>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Affiche les informations d'une série.
        /// Call for GET 'shows/display'.
        /// </summary>
        /// <param name="id">ID de la série. Vous pouvez en mettre plusieurs en les séparant par un virgule (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB. Vous pouvez en mettre plusieurs en les séparant par un virgule (Facultatif si id renseigné)</param>
        public void ShowDisplay(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("GET", "shows/display", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche les épisodes d'une série.
        /// Call for GET 'shows/episodes'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        /// <param name="season">Numéro de la saison (Facultatif)</param>
        /// <param name="episode">Numéro de l&#x27;épisode (Facultatif)</param>
        /// <param name="subtitles">Affiche les sous-titres si renseigné (Facultatif)</param>
        public void ShowEpisode(string id, string thetvdb_id, string season, string episode, string subtitles) {
            var parameters = new List<KVP<string, string>>(5);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("season", season));
            parameters.Add(new KVP<string, string>("episode", episode));
            parameters.Add(new KVP<string, string>("subtitles", subtitles));
            var response = this.client.ExecuteQuery("GET", "shows/episodes", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Ajoute une série favorite sur le profil du membre identifié.
        /// Call for POST 'shows/favorite'.
        /// </summary>
        /// <param name="id">ID de la série à ajouter.</param>
        public void SetShowAsFavorite(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("POST", "shows/favorite", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime une série favorite du profil du membre identifié.
        /// Call for DELETE 'shows/favorite'.
        /// </summary>
        /// <param name="id">ID de la série à supprimer.</param>
        public void DeleteShowFavorite(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "shows/favorite", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les séries favorites du membre.
        /// Call for GET 'shows/favorites'.
        /// </summary>
        /// <param name="id">ID du membre, facultatif, si non renseigné utilise le membre identifié.</param>
        public void GetFavoriteShows(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("GET", "shows/favorites", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Affiche la liste de toutes les séries.
        /// Call for GET 'shows/list'.
        /// </summary>
        /// <param name="order">Spécifie l&#x27;ordre de retour : alphabetical, popularity, followers (facultatif)</param>
        /// <param name="since">N&#x27;afficher que les séries modifiées à partir de cette date (timestamp UNIX — facultatif)</param>
        public void ShowList(string order, string since) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("order", order));
            parameters.Add(new KVP<string, string>("since", since));
            var response = this.client.ExecuteQuery("GET", "shows/list", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Note une série.
        /// Call for POST 'shows/note'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        /// <param name="note">Note attribuée de 1 à 5</param>
        public void ShowNote(string id, string thetvdb_id, string note) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("note", note));
            var response = this.client.ExecuteQuery("POST", "shows/note", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime une note d'une série.
        /// Call for DELETE 'shows/note'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public void DeleteShowNote(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("DELETE", "shows/note", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les images de la série, ajoutées par les membres de BetaSeries.
        /// Call for GET 'shows/pictures'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public Srk.BetaseriesApi.ShowPicture ShowPicture(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("GET", "shows/pictures", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.ShowPicture>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Affiche une série au hasard.
        /// Call for GET 'shows/random'.
        /// </summary>
        /// <param name="nb">Nombre de séries à afficher, par défaut 1</param>
        /// <param name="summary">Retourne uniquement les infos essentielles de la série (Défaut false)</param>
        public void ShowRandom(string nb, string summary) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("nb", nb));
            parameters.Add(new KVP<string, string>("summary", summary));
            var response = this.client.ExecuteQuery("GET", "shows/random", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Créer une recommandation d'une série d'un membre pour un ami.
        /// Call for POST 'shows/recommendation'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        /// <param name="to">ID du membre ami</param>
        /// <param name="comments">Commentaires pour l&#x27;ami (Facultatif)</param>
        public void ShowRecommendation(string id, string thetvdb_id, string to, string comments) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("to", to));
            parameters.Add(new KVP<string, string>("comments", comments));
            var response = this.client.ExecuteQuery("POST", "shows/recommendation", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime une recommandation d'une série envoyée ou reçue.
        /// Call for DELETE 'shows/recommendation'.
        /// </summary>
        /// <param name="id">ID de la recommandation</param>
        public void DeleteShowRecommendation(string id) {
            var parameters = new List<KVP<string, string>>(1);
            parameters.Add(new KVP<string, string>("id", id));
            var response = this.client.ExecuteQuery("DELETE", "shows/recommendation", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les recommandations reçues par l'utilisateur identifié.
        /// Call for GET 'shows/recommendations'.
        /// </summary>
        public void ShowRecommendation() {
            var parameters = new List<KVP<string, string>>(0);
            var response = this.client.ExecuteQuery("GET", "shows/recommendations", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Recherche une série.
        /// Call for GET 'shows/search'.
        /// </summary>
        /// <param name="title">Titre recherché</param>
        /// <param name="summary">Retourne uniquement les infos essentielles de la série (Défaut false)</param>
        /// <param name="order">Ordre de retour (title|popularity|followers), par défaut title</param>
        /// <param name="nbpp">Nombre de résultats par page, par défaut 5, maximum 100</param>
        /// <param name="page">Numéro de la page, par défaut 1</param>
        public void ShowSearch(string title, string summary, TitlePopularityFollower order, string nbpp, string page) {
            var parameters = new List<KVP<string, string>>(5);
            parameters.Add(new KVP<string, string>("title", title));
            parameters.Add(new KVP<string, string>("summary", summary));
            parameters.Add(new KVP<string, string>("order", order.ToString()));
            parameters.Add(new KVP<string, string>("nbpp", nbpp));
            parameters.Add(new KVP<string, string>("page", page));
            var response = this.client.ExecuteQuery("GET", "shows/search", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Ajoute une série dans le compte du membre.
        /// Call for POST 'shows/show'.
        /// </summary>
        /// <param name="id">ID de la série. Vous pouvez en mettre plusieurs en les séparant par un virgule (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB. Vous pouvez en mettre plusieurs en les séparant par un virgule (Facultatif si id renseigné)</param>
        /// <param name="episode_id">ID du dernier épisode vu. Si plusieurs séries, l&#x27;ordre des épisodes doit être exactement le même (Facultatif)</param>
        public void ShowShow(string id, string thetvdb_id, string episode_id) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            parameters.Add(new KVP<string, string>("episode_id", episode_id));
            var response = this.client.ExecuteQuery("POST", "shows/show", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Supprime une série du compte du membre.
        /// Call for DELETE 'shows/show'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public void DeleteShowShow(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("DELETE", "shows/show", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les séries marquées similaires par les membres de BetaSeries.
        /// Call for GET 'shows/similars'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public void ShowSimilar(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("GET", "shows/similars", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }

        /// <summary>
        /// Récupère les vidéos associées à la série par les membres de BetaSeries.
        /// Call for GET 'shows/videos'.
        /// </summary>
        /// <param name="id">ID de la série (Facultatif si thetvdb_id renseigné)</param>
        /// <param name="thetvdb_id">ID de la série sur TheTVDB (Facultatif si id renseigné)</param>
        public void ShowVideo(string id, string thetvdb_id) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("thetvdb_id", thetvdb_id));
            var response = this.client.ExecuteQuery("GET", "shows/videos", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse>(response);
            this.client.HandleErrors(result);
        }
    }

    public partial class BetaseriesSubtitlesClient {
        private readonly BetaseriesClient client;

        public BetaseriesSubtitlesClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Affiche les sous-titres pour un épisode donné.
        /// Call for GET 'subtitles/episode'.
        /// </summary>
        /// <param name="id">ID de l&#x27;épisode</param>
        /// <param name="language">N&#x27;affiche que certaines langues : all|vovf|vo|vf (Facultatif)</param>
        public Srk.BetaseriesApi.SubtitleEpisode SubtitleEpisode(string id, SubtitleFilter language) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("language", language.ToString()));
            var response = this.client.ExecuteQuery("GET", "subtitles/episode", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.SubtitleEpisode>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Affiche les derniers sous-titres récupérés par BetaSeries.
        /// Call for GET 'subtitles/last'.
        /// </summary>
        /// <param name="number">Nombre de sous-titres, maximum 100</param>
        /// <param name="language">N&#x27;affiche que certaines langues : all|vovf|vo|vf (Facultatif)</param>
        public Srk.BetaseriesApi.SubtitleLast SubtitleLast(string number, SubtitleFilter language) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("number", number));
            parameters.Add(new KVP<string, string>("language", language.ToString()));
            var response = this.client.ExecuteQuery("GET", "subtitles/last", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.SubtitleLast>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Reporte des sous-titres comme incorrects pour se faire supprimer de la liste.
        /// Call for POST 'subtitles/report'.
        /// </summary>
        /// <param name="id">ID du sous-titre</param>
        /// <param name="reason">Raison pour laquelle le sous-titre n&#x27;est pas correct</param>
        public Srk.BetaseriesApi.SubtitleReport SubtitleReport(string id, string reason) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("reason", reason));
            var response = this.client.ExecuteQuery("POST", "subtitles/report", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.SubtitleReport>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Affiche les sous-titres pour une série donnée.
        /// Call for GET 'subtitles/show'.
        /// </summary>
        /// <param name="id">ID de la série</param>
        /// <param name="language">N&#x27;affiche que certaines langues : all|vovf|vo|vf (Facultatif)</param>
        public Srk.BetaseriesApi.SubtitleShow SubtitleShow(string id, SubtitleFilter language) {
            var parameters = new List<KVP<string, string>>(2);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("language", language.ToString()));
            var response = this.client.ExecuteQuery("GET", "subtitles/show", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.SubtitleShow>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }
    }

    public partial class BetaseriesTimelineClient {
        private readonly BetaseriesClient client;

        public BetaseriesTimelineClient(BetaseriesClient client) {
            this.client = client;
        }


        /// <summary>
        /// Affiche les derniers évènements des amis du membre identifié.
        /// Call for GET 'timeline/friends'.
        /// </summary>
        /// <param name="nbpp">Nombre d&#x27;évènements par page, maximum 100</param>
        /// <param name="since_id">ID du dernier évènement reçu (Facultatif)</param>
        /// <param name="types">Types d&#x27;évènements à retourner, séparés par une virgule (Facultatif)</param>
        public Srk.BetaseriesApi.TimelineFriend TimelineFriend(string nbpp, string since_id, string types) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("nbpp", nbpp));
            parameters.Add(new KVP<string, string>("since_id", since_id));
            parameters.Add(new KVP<string, string>("types", types));
            var response = this.client.ExecuteQuery("GET", "timeline/friends", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.TimelineFriend>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Affiche les derniers évènements du site.
        /// Call for GET 'timeline/home'.
        /// </summary>
        /// <param name="nbpp">Nombre d&#x27;évènements par page, maximum 100</param>
        /// <param name="since_id">ID du dernier évènement reçu (Facultatif)</param>
        /// <param name="types">Types d&#x27;évènements à retourner, séparés par une virgule (Facultatif)</param>
        public Srk.BetaseriesApi.TimelineHome TimelineHome(string nbpp, string since_id, string types) {
            var parameters = new List<KVP<string, string>>(3);
            parameters.Add(new KVP<string, string>("nbpp", nbpp));
            parameters.Add(new KVP<string, string>("since_id", since_id));
            parameters.Add(new KVP<string, string>("types", types));
            var response = this.client.ExecuteQuery("GET", "timeline/home", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.TimelineHome>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }

        /// <summary>
        /// Affiche les derniers évènements du membre spécifié.
        /// Call for GET 'timeline/member'.
        /// </summary>
        /// <param name="id">ID du membre</param>
        /// <param name="nbpp">Nombre d&#x27;évènements par page, maximum 100</param>
        /// <param name="since_id">ID du dernier évènement reçu (Facultatif)</param>
        /// <param name="types">Types d&#x27;évènements à retourner, séparés par une virgule (Facultatif)</param>
        public Srk.BetaseriesApi.TimelineMember TimelineMember(string id, string nbpp, string since_id, string types) {
            var parameters = new List<KVP<string, string>>(4);
            parameters.Add(new KVP<string, string>("id", id));
            parameters.Add(new KVP<string, string>("nbpp", nbpp));
            parameters.Add(new KVP<string, string>("since_id", since_id));
            parameters.Add(new KVP<string, string>("types", types));
            var response = this.client.ExecuteQuery("GET", "timeline/member", parameters);
            
            var result = JsonConvert.DeserializeObject<BaseResponse<Srk.BetaseriesApi.TimelineMember>>(response);
            this.client.HandleErrors(result);
            return result.Data;
        }
    }
}

#endregion


/*
Session IDictionary`2
Errors CompilerErrorCollection
CurrentIndent String
Microsoft.VisualStudio.TextTemplating.11.0, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.VisualStudio.TextTemplating.TextTransformation
*/


