//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Srk.BetaseriesApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Srk.BetaseriesApi.Resources.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API key, contact the administrator/developer..
        /// </summary>
        public static string ErrorDetail1001 {
            get {
                return ResourceManager.GetString("ErrorDetail1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type..
        /// </summary>
        public static string ErrorDetail1002 {
            get {
                return ResourceManager.GetString("ErrorDetail1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action, you may want to update the application..
        /// </summary>
        public static string ErrorDetail1003 {
            get {
                return ResourceManager.GetString("ErrorDetail1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such session. Authenticate again..
        /// </summary>
        public static string ErrorDetail2001 {
            get {
                return ResourceManager.GetString("ErrorDetail2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not accept to share this..
        /// </summary>
        public static string ErrorDetail2002 {
            get {
                return ResourceManager.GetString("ErrorDetail2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This show is already associated with the account..
        /// </summary>
        public static string ErrorDetail2003 {
            get {
                return ResourceManager.GetString("ErrorDetail2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This show is not associated with the account..
        /// </summary>
        public static string ErrorDetail2004 {
            get {
                return ResourceManager.GetString("ErrorDetail2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode not already seen..
        /// </summary>
        public static string ErrorDetail2005 {
            get {
                return ResourceManager.GetString("ErrorDetail2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two users are not friends..
        /// </summary>
        public static string ErrorDetail2006 {
            get {
                return ResourceManager.GetString("ErrorDetail2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user options.
        /// </summary>
        public static string ErrorDetail2007 {
            get {
                return ResourceManager.GetString("ErrorDetail2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing input data, you may want to update the application..
        /// </summary>
        public static string ErrorDetail3001 {
            get {
                return ResourceManager.GetString("ErrorDetail3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 2 characters..
        /// </summary>
        public static string ErrorDetail3002 {
            get {
                return ResourceManager.GetString("ErrorDetail3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number expected..
        /// </summary>
        public static string ErrorDetail3003 {
            get {
                return ResourceManager.GetString("ErrorDetail3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        public static string ErrorDetail3004 {
            get {
                return ResourceManager.GetString("ErrorDetail3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden characters..
        /// </summary>
        public static string ErrorDetail3005 {
            get {
                return ResourceManager.GetString("ErrorDetail3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string ErrorDetail3006 {
            get {
                return ResourceManager.GetString("ErrorDetail3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such show..
        /// </summary>
        public static string ErrorDetail4001 {
            get {
                return ResourceManager.GetString("ErrorDetail4001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such user..
        /// </summary>
        public static string ErrorDetail4002 {
            get {
                return ResourceManager.GetString("ErrorDetail4002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string ErrorDetail4003 {
            get {
                return ResourceManager.GetString("ErrorDetail4003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists..
        /// </summary>
        public static string ErrorDetail4004 {
            get {
                return ResourceManager.GetString("ErrorDetail4004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No related error message; error code is &apos;{0}&apos;..
        /// </summary>
        public static string ErrorDetailUnknown {
            get {
                return ResourceManager.GetString("ErrorDetailUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API error.
        /// </summary>
        public static string ErrorType1 {
            get {
                return ResourceManager.GetString("ErrorType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User error.
        /// </summary>
        public static string ErrorType2 {
            get {
                return ResourceManager.GetString("ErrorType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input error.
        /// </summary>
        public static string ErrorType3 {
            get {
                return ResourceManager.GetString("ErrorType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data error.
        /// </summary>
        public static string ErrorType4 {
            get {
                return ResourceManager.GetString("ErrorType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string ErrorTypeUnknown {
            get {
                return ResourceManager.GetString("ErrorTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        public static string TypeAndDetailSeparator {
            get {
                return ResourceManager.GetString("TypeAndDetailSeparator", resourceCulture);
            }
        }
    }
}
