//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Srk.BetaseriesApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Srk.BetaseriesApi.Resources.GeneralStrings", typeof(GeneralStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your 10th show added, you start to have an interesting profile..
        /// </summary>
        public static string BadgeDesc_Amateur {
            get {
                return ResourceManager.GetString("BadgeDesc_Amateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your beautiful face is now on your profile, it&apos;s for the drag?.
        /// </summary>
        public static string BadgeDesc_BeauxYeux {
            get {
                return ResourceManager.GetString("BadgeDesc_BeauxYeux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s great support! 10 adverts watched!.
        /// </summary>
        public static string BadgeDesc_Bienfaiteur {
            get {
                return ResourceManager.GetString("BadgeDesc_Bienfaiteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You suggested 25 times your friends to follow a series, did they listen?.
        /// </summary>
        public static string BadgeDesc_BlogueurInfluent {
            get {
                return ResourceManager.GetString("BadgeDesc_BlogueurInfluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You follow 5 fantastic shows; beware of aliens..
        /// </summary>
        public static string BadgeDesc_CapitaineSpock {
            get {
                return ResourceManager.GetString("BadgeDesc_CapitaineSpock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched 25 shows, you start to get hooked, beware! .
        /// </summary>
        public static string BadgeDesc_Confirme {
            get {
                return ResourceManager.GetString("BadgeDesc_Confirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You watched your first episode. Welcome to BetaSeries! .
        /// </summary>
        public static string BadgeDesc_Debutant {
            get {
                return ResourceManager.GetString("BadgeDesc_Debutant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You use your little hands full of fingers to improve the ecosystem of BetaSeries. Thank you so much!.
        /// </summary>
        public static string BadgeDesc_Developpeur {
            get {
                return ResourceManager.GetString("BadgeDesc_Developpeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for supporting BetaSeries by watching a video advert..
        /// </summary>
        public static string BadgeDesc_Donateur {
            get {
                return ResourceManager.GetString("BadgeDesc_Donateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 drama in your profile? Don&apos;t forget to bring tissues next time..
        /// </summary>
        public static string BadgeDesc_DramaQueen {
            get {
                return ResourceManager.GetString("BadgeDesc_DramaQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dare to watch series after 3 am in full week....
        /// </summary>
        public static string BadgeDesc_EcoleBuissoniere {
            get {
                return ResourceManager.GetString("BadgeDesc_EcoleBuissoniere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One week, 10 episodes. You&apos;re gonna have to relativize your life..
        /// </summary>
        public static string BadgeDesc_Einstein {
            get {
                return ResourceManager.GetString("BadgeDesc_Einstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You created a character page on BetaSeries. .
        /// </summary>
        public static string BadgeDesc_Fiche {
            get {
                return ResourceManager.GetString("BadgeDesc_Fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You watched the same episode as 75 members this day. You&apos;re fashionable..
        /// </summary>
        public static string BadgeDesc_Flashmob {
            get {
                return ResourceManager.GetString("BadgeDesc_Flashmob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first post in our forum!.
        /// </summary>
        public static string BadgeDesc_ForumStarter {
            get {
                return ResourceManager.GetString("BadgeDesc_ForumStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for illustrating a tv show. You can continue!.
        /// </summary>
        public static string BadgeDesc_FreshPaint {
            get {
                return ResourceManager.GetString("BadgeDesc_FreshPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to you, already 10 sub-titles were reported as inadequate..
        /// </summary>
        public static string BadgeDesc_Gendarme {
            get {
                return ResourceManager.GetString("BadgeDesc_Gendarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you spend your evenings watching 4 episodes, don&apos;t be surprised by what we say..
        /// </summary>
        public static string BadgeDesc_Glandeur {
            get {
                return ResourceManager.GetString("BadgeDesc_Glandeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your 100 files downloaded subtitles....
        /// </summary>
        public static string BadgeDesc_HadopiMaster {
            get {
                return ResourceManager.GetString("BadgeDesc_HadopiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friends have performed 30 operations in the last 24 hours, they are loyal customers..
        /// </summary>
        public static string BadgeDesc_Hyperactifs {
            get {
                return ResourceManager.GetString("BadgeDesc_Hyperactifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 comedy shows is pretty scary, don&apos;t forget to breathe..
        /// </summary>
        public static string BadgeDesc_JerrySeinfeld {
            get {
                return ResourceManager.GetString("BadgeDesc_JerrySeinfeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You prefered to watch an episode instead of having a family dinner. We understand..
        /// </summary>
        public static string BadgeDesc_JoyeuxNoel {
            get {
                return ResourceManager.GetString("BadgeDesc_JoyeuxNoel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You watched 10 episodes of 10 different series, it&apos;s a good start..
        /// </summary>
        public static string BadgeDesc_Junior {
            get {
                return ResourceManager.GetString("BadgeDesc_Junior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s it, you saw more than 1,000 episodes of TV series. You dirty geek..
        /// </summary>
        public static string BadgeDesc_LeMillier {
            get {
                return ResourceManager.GetString("BadgeDesc_LeMillier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One hundred movies in your list, you&apos;ll have to think about going to see a 3D session. How does it not?.
        /// </summary>
        public static string BadgeDesc_Lunettes3d {
            get {
                return ResourceManager.GetString("BadgeDesc_Lunettes3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve watched 6 episodes in full Sunday is a grand slam!.
        /// </summary>
        public static string BadgeDesc_Marathonien {
            get {
                return ResourceManager.GetString("BadgeDesc_Marathonien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You watched more than 35 hours of episodes. It is the struggle....
        /// </summary>
        public static string BadgeDesc_MartineAubry {
            get {
                return ResourceManager.GetString("BadgeDesc_MartineAubry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 reciprocal friends. Friendship is beautiful, especially when one is aware..
        /// </summary>
        public static string BadgeDesc_MeilleurAmi {
            get {
                return ResourceManager.GetString("BadgeDesc_MeilleurAmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven nights, seven episodes. You have your habits as we can see....
        /// </summary>
        public static string BadgeDesc_Noctambule {
            get {
                return ResourceManager.GetString("BadgeDesc_Noctambule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You registered during the first year of betaseries..
        /// </summary>
        public static string BadgeDesc_OldSchool {
            get {
                return ResourceManager.GetString("BadgeDesc_OldSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You invited a friend on betaseries. Now you have to look after him/her..
        /// </summary>
        public static string BadgeDesc_Parrain {
            get {
                return ResourceManager.GetString("BadgeDesc_Parrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve posted 25 comments on BetaSeries, what a bla bla!.
        /// </summary>
        public static string BadgeDesc_PetitBavard {
            get {
                return ResourceManager.GetString("BadgeDesc_PetitBavard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These last twelve hours you&apos;ve watched 4 episodes. Make something of your life..
        /// </summary>
        public static string BadgeDesc_Planque {
            get {
                return ResourceManager.GetString("BadgeDesc_Planque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You turned on your Facebook account BetaSeries, you are social..
        /// </summary>
        public static string BadgeDesc_PokeHerFace {
            get {
                return ResourceManager.GetString("BadgeDesc_PokeHerFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 episodes of the same show... We have a show to catch up to what I see..
        /// </summary>
        public static string BadgeDesc_Rattrapage {
            get {
                return ResourceManager.GetString("BadgeDesc_Rattrapage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 TV shows, nothing can stop you. Go on, after all, it does not bother us..
        /// </summary>
        public static string BadgeDesc_Senior {
            get {
                return ResourceManager.GetString("BadgeDesc_Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A month has passed and 30 episodes have been watched, you a easy double-click..
        /// </summary>
        public static string BadgeDesc_Serievore {
            get {
                return ResourceManager.GetString("BadgeDesc_Serievore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 people have added you to their friends, Michel Drucker had better behave..
        /// </summary>
        public static string BadgeDesc_Superstar {
            get {
                return ResourceManager.GetString("BadgeDesc_Superstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woh, 12 badges on your profile, we won&apos;t have more room for others..
        /// </summary>
        public static string BadgeDesc_Surbooking {
            get {
                return ResourceManager.GetString("BadgeDesc_Surbooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Twitter account is configured, you are part of the great family of microblogging..
        /// </summary>
        public static string BadgeDesc_Twittos {
            get {
                return ResourceManager.GetString("BadgeDesc_Twittos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been a year that you are on BetaSeries, it&apos;s worth celebrating..
        /// </summary>
        public static string BadgeDesc_VieuxBriscard {
            get {
                return ResourceManager.GetString("BadgeDesc_VieuxBriscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown badge.
        /// </summary>
        public static string Badges_ {
            get {
                return ResourceManager.GetString("Badges_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amateur.
        /// </summary>
        public static string Badges_Amateur {
            get {
                return ResourceManager.GetString("Badges_Amateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beautiful eyes.
        /// </summary>
        public static string Badges_BeauxYeux {
            get {
                return ResourceManager.GetString("Badges_BeauxYeux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienfaiteur.
        /// </summary>
        public static string Badges_Bienfaiteur {
            get {
                return ResourceManager.GetString("Badges_Bienfaiteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Influential blogger.
        /// </summary>
        public static string Badges_BlogueurInfluent {
            get {
                return ResourceManager.GetString("Badges_BlogueurInfluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Spock.
        /// </summary>
        public static string Badges_CapitaineSpock {
            get {
                return ResourceManager.GetString("Badges_CapitaineSpock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Badges_Confirme {
            get {
                return ResourceManager.GetString("Badges_Confirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noobie.
        /// </summary>
        public static string Badges_Debutant {
            get {
                return ResourceManager.GetString("Badges_Debutant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string Badges_Developpeur {
            get {
                return ResourceManager.GetString("Badges_Developpeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donator.
        /// </summary>
        public static string Badges_Donateur {
            get {
                return ResourceManager.GetString("Badges_Donateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama Queen.
        /// </summary>
        public static string Badges_DramaQueen {
            get {
                return ResourceManager.GetString("Badges_DramaQueen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School truancy.
        /// </summary>
        public static string Badges_EcoleBuissoniere {
            get {
                return ResourceManager.GetString("Badges_EcoleBuissoniere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstein.
        /// </summary>
        public static string Badges_Einstein {
            get {
                return ResourceManager.GetString("Badges_Einstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.
        /// </summary>
        public static string Badges_Fiche {
            get {
                return ResourceManager.GetString("Badges_Fiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashmob.
        /// </summary>
        public static string Badges_Flashmob {
            get {
                return ResourceManager.GetString("Badges_Flashmob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum noobie.
        /// </summary>
        public static string Badges_ForumStarter {
            get {
                return ResourceManager.GetString("Badges_ForumStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh paint.
        /// </summary>
        public static string Badges_FreshPaint {
            get {
                return ResourceManager.GetString("Badges_FreshPaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gendarme.
        /// </summary>
        public static string Badges_Gendarme {
            get {
                return ResourceManager.GetString("Badges_Gendarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layabout.
        /// </summary>
        public static string Badges_Glandeur {
            get {
                return ResourceManager.GetString("Badges_Glandeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hadopi Master.
        /// </summary>
        public static string Badges_HadopiMaster {
            get {
                return ResourceManager.GetString("Badges_HadopiMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperactives.
        /// </summary>
        public static string Badges_Hyperactifs {
            get {
                return ResourceManager.GetString("Badges_Hyperactifs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jerry Seinfeld.
        /// </summary>
        public static string Badges_JerrySeinfeld {
            get {
                return ResourceManager.GetString("Badges_JerrySeinfeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merry Christmas.
        /// </summary>
        public static string Badges_JoyeuxNoel {
            get {
                return ResourceManager.GetString("Badges_JoyeuxNoel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior.
        /// </summary>
        public static string Badges_Junior {
            get {
                return ResourceManager.GetString("Badges_Junior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le millier.
        /// </summary>
        public static string Badges_LeMillier {
            get {
                return ResourceManager.GetString("Badges_LeMillier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D glasses.
        /// </summary>
        public static string Badges_Lunettes3d {
            get {
                return ResourceManager.GetString("Badges_Lunettes3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathonien.
        /// </summary>
        public static string Badges_Marathonien {
            get {
                return ResourceManager.GetString("Badges_Marathonien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martine Aubry.
        /// </summary>
        public static string Badges_MartineAubry {
            get {
                return ResourceManager.GetString("Badges_MartineAubry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best friend.
        /// </summary>
        public static string Badges_MeilleurAmi {
            get {
                return ResourceManager.GetString("Badges_MeilleurAmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night owl.
        /// </summary>
        public static string Badges_Noctambule {
            get {
                return ResourceManager.GetString("Badges_Noctambule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old-school.
        /// </summary>
        public static string Badges_OldSchool {
            get {
                return ResourceManager.GetString("Badges_OldSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parrain.
        /// </summary>
        public static string Badges_Parrain {
            get {
                return ResourceManager.GetString("Badges_Parrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatty.
        /// </summary>
        public static string Badges_PetitBavard {
            get {
                return ResourceManager.GetString("Badges_PetitBavard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holed.
        /// </summary>
        public static string Badges_Planque {
            get {
                return ResourceManager.GetString("Badges_Planque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poke her face.
        /// </summary>
        public static string Badges_PokeHerFace {
            get {
                return ResourceManager.GetString("Badges_PokeHerFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking up.
        /// </summary>
        public static string Badges_Rattrapage {
            get {
                return ResourceManager.GetString("Badges_Rattrapage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior.
        /// </summary>
        public static string Badges_Senior {
            get {
                return ResourceManager.GetString("Badges_Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serievore.
        /// </summary>
        public static string Badges_Serievore {
            get {
                return ResourceManager.GetString("Badges_Serievore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superstar.
        /// </summary>
        public static string Badges_Superstar {
            get {
                return ResourceManager.GetString("Badges_Superstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surbooking.
        /// </summary>
        public static string Badges_Surbooking {
            get {
                return ResourceManager.GetString("Badges_Surbooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twittos.
        /// </summary>
        public static string Badges_Twittos {
            get {
                return ResourceManager.GetString("Badges_Twittos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Badges_Unknown {
            get {
                return ResourceManager.GetString("Badges_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old hand.
        /// </summary>
        public static string Badges_VieuxBriscard {
            get {
                return ResourceManager.GetString("Badges_VieuxBriscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} earned a badge: {1}..
        /// </summary>
        public static string TimelineItemType_BadgeEarned_ {
            get {
                return ResourceManager.GetString("TimelineItemType_BadgeEarned_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commented.
        /// </summary>
        public static string TimelineItemType_Comment {
            get {
                return ResourceManager.GetString("TimelineItemType_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on {1}..
        /// </summary>
        public static string TimelineItemType_Comment_ {
            get {
                return ResourceManager.GetString("TimelineItemType_Comment_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on {1}..
        /// </summary>
        public static string TimelineItemType_CommentOnEpisode_ {
            get {
                return ResourceManager.GetString("TimelineItemType_CommentOnEpisode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on {1}&apos;s profile..
        /// </summary>
        public static string TimelineItemType_CommentOnMember_ {
            get {
                return ResourceManager.GetString("TimelineItemType_CommentOnMember_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} commented on {1}..
        /// </summary>
        public static string TimelineItemType_CommentOnShow_ {
            get {
                return ResourceManager.GetString("TimelineItemType_CommentOnShow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added a friend.
        /// </summary>
        public static string TimelineItemType_FriendAdded {
            get {
                return ResourceManager.GetString("TimelineItemType_FriendAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now {1}&apos;s friend..
        /// </summary>
        public static string TimelineItemType_FriendAdded_ {
            get {
                return ResourceManager.GetString("TimelineItemType_FriendAdded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is no more a friend of.
        /// </summary>
        public static string TimelineItemType_FriendRemoved {
            get {
                return ResourceManager.GetString("TimelineItemType_FriendRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no more {1}&apos;s friend..
        /// </summary>
        public static string TimelineItemType_FriendRemoved_ {
            get {
                return ResourceManager.GetString("TimelineItemType_FriendRemoved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watched.
        /// </summary>
        public static string TimelineItemType_MarkedAs {
            get {
                return ResourceManager.GetString("TimelineItemType_MarkedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} watched {1}..
        /// </summary>
        public static string TimelineItemType_MarkedAs_ {
            get {
                return ResourceManager.GetString("TimelineItemType_MarkedAs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recommanded.
        /// </summary>
        public static string TimelineItemType_Recommendation {
            get {
                return ResourceManager.GetString("TimelineItemType_Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recommended {1}..
        /// </summary>
        public static string TimelineItemType_Recommendation_ {
            get {
                return ResourceManager.GetString("TimelineItemType_Recommendation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} accepted {2}&apos;s recommendation to watch {1}..
        /// </summary>
        public static string TimelineItemType_RecommendationAccepted_ {
            get {
                return ResourceManager.GetString("TimelineItemType_RecommendationAccepted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rejected {2}&apos;s recommendation to watch {1}..
        /// </summary>
        public static string TimelineItemType_RecommendationDenied_ {
            get {
                return ResourceManager.GetString("TimelineItemType_RecommendationDenied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to added a show.
        /// </summary>
        public static string TimelineItemType_ShowAdded {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added {1}..
        /// </summary>
        public static string TimelineItemType_ShowAdded_ {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowAdded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archived.
        /// </summary>
        public static string TimelineItemType_ShowArchived {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} archived {1}..
        /// </summary>
        public static string TimelineItemType_ShowArchived_ {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowArchived_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed a show.
        /// </summary>
        public static string TimelineItemType_ShowRemoved {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed {1}..
        /// </summary>
        public static string TimelineItemType_ShowRemoved_ {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowRemoved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unarchived.
        /// </summary>
        public static string TimelineItemType_ShowUnarchived {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowUnarchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unarchived {1}..
        /// </summary>
        public static string TimelineItemType_ShowUnarchived_ {
            get {
                return ResourceManager.GetString("TimelineItemType_ShowUnarchived_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {2} {1}.
        /// </summary>
        public static string TimelineItemType_Unknown_ {
            get {
                return ResourceManager.GetString("TimelineItemType_Unknown_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated {1}..
        /// </summary>
        public static string TimelineItemType_Update_ {
            get {
                return ResourceManager.GetString("TimelineItemType_Update_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registered on betaseries..
        /// </summary>
        public static string TimelineItemType_UserRegistered {
            get {
                return ResourceManager.GetString("TimelineItemType_UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now a member of betaseries..
        /// </summary>
        public static string TimelineItemType_UserRegistered_ {
            get {
                return ResourceManager.GetString("TimelineItemType_UserRegistered_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changed the wiki page {1}..
        /// </summary>
        public static string TimelineItemType_WikiUpdate_ {
            get {
                return ResourceManager.GetString("TimelineItemType_WikiUpdate_", resourceCulture);
            }
        }
    }
}
